language: crystal
cache: shards
crystal:
  - latest
  - nightly

script:
  - crystal spec
  - crystal tool format --check

# TODO: deploy docs
# after_success:
  # - if [[ "$TRAVIS_BRANCH" == "master" ]]; then crystal docs && netlify deploy --prod; fi
